[package]
name = "gotham-benchmarks"
version = "0.1.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
futures = "0.1"
gotham = { git = "https://github.com/ChristophWurst/gotham.git", branch = "refactor/tokio-reform" }
hyper = "*"
mime = "*"
primal = "0.2.3"
